/*
 *  Copyright (C) <2024> <XiaoMoMi>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.momirealms.customnameplates.common.event;

import net.kyori.adventure.text.Component;

/**
 * An event that represents feedback generated by a command execution.
 * This event contains the sender of the command, the associated key, and the feedback message.
 */
public interface CommandFeedbackEvent<C> extends NameplatesEvent, Cancellable {

    /**
     * Gets the sender of the command that triggered this event.
     *
     * @return the sender (e.g., player or entity) of the command.
     */
    @Param(0)
    C sender();

    /**
     * Gets the key associated with the feedback message.
     * This key may be used to identify the context or specific type of feedback.
     *
     * @return the key for the feedback message.
     */
    @Param(1)
    String key();

    /**
     * Gets the feedback message that will be sent in response to the command.
     * The message is represented by a {@link Component}, which allows for rich text formatting.
     *
     * @return the feedback message to be displayed or logged.
     */
    @Param(2)
    Component message();
}
