name: CustomNameplates
version: '${version}'
main: net.momirealms.customnameplates.CustomNameplates
api-version: 1.17
authors: [ XiaoMoMi ]
folia-supported: true
depend:
  - ProtocolLib
  - PlaceholderAPI
softdepend:
  - ItemsAdder
  - TAB
  - Oraxen
  - TrChat
  - MagicCosmetics
  - CMI
  - LibsDisguises
commands:
  customnameplates:
    usage: /customnameplates
    aliases:
      - nameplates
  chatbubbles:
    usage: /chatbubbles
    aliases:
      - bubbles

permissions:
  nameplates.*:
    description: Gives access to all nameplates commands
    children:
      nameplates.reload: true
      nameplates.forceequip: true
      nameplates.forceunequip: true
      nameplates.help: true
      nameplates.unequip: true
      nameplates.preview: true
      nameplates.list: true
      nameplates.about: true

  nameplates.reload:
    default: op
  nameplates.forceequip:
    default: op
  nameplates.forceunequip:
    default: op
  nameplates.help:
    default: op
  nameplates.about:
    default: op
  nameplates.unequip:
    default: true
  nameplates.preview:
    default: true
  nameplates.list:
    default: true
  nameplates.equip:
    default: true

  bubbles.*:
    description: Gives access to all bubbles commands
    children:
      bubbles.unequip: true
      bubbles.equip: true
      bubbles.help: true
      bubbles.forceequip: true
      bubbles.forceunequip: true
      bubbles.list: true
      bubbles.use: true

  bubbles.help:
    default: op
  bubbles.equip:
    default: true
  bubbles.unequip:
    default: true
  bubbles.list:
    default: true
  bubbles.forceequip:
    default: op
  bubbles.forceunequip:
    default: op
  bubbles.use:
    default: true