# You can create as many sections as you want for more bossbars
bossbar_1:
  # Color (BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW)
  color: YELLOW
  # Overlay (It can be either "progress", "notched_6", "notched_10", "notched_12" or "notched_20")
  overlay: PROGRESS
  # The frequency of checking conditions for a bar, measured in ticks
  check-frequency: 10
  conditions:
    permission: "bossbar.show"
  # Bar's content would be shown as the following order
  text-display-order:
    1:
      # Measured in ticks
      duration: 100
      # Text content
      text: '%nameplates_background_hello%'
      # The frequency of refreshing the text, the lower the value is, the faster the placeholders are updated
      # measured in ticks, -1 = disable refreshing
      refresh-frequency: -1
    2:
      duration: 200
      text: '%nameplates_background_time%  %nameplates_background_location%  %nameplates_background_weather%'
      refresh-frequency: 1
    3:
      duration: 100
      text: '%nameplates_background_update%'
      refresh-frequency: -1
      # Optional
      # When enabling conditions, make sure that players would see at least one in the order,
      # otherwise it will fall into a dead cycle
      # If your player doesn't meet the conditions, it would be skipped
      # This condition would only be checked once until the next turn
      conditions:
        permission: nameplates.admin
        equals:
          value1: '%nameplates_is-latest%'
          value2: 'false'