# Requirements for sending the bubble
requirements:
  permission: bubbles.use
  self-disguised: false
  '!gamemode': spectator
  potion-effect: "INVISIBILITY<0"

# blacklist channels
blacklist-channels:
  - Private
  - Staff

# ALL: all the players can see the bubble
# JOINED: players in the same channel can see each other's bubble
# CAN_JOIN: players that have permission to certain channels would see the bubble in that channel
channel-mode: ALL

# Default bubble to display if player's bubble is "none"
default-bubble: 'chat'

# Text format when bubble is "none"
default-format:
  start: '<gradient:#F5F5F5:#E1FFFF:#F5F5F5><u>'
  end: '<!u></gradient>'

# Add additional prefix and suffix to the text
text-prefix: ''
text-suffix: ''

# Space between two bubbles
line-spacing: 0.4

# This decides where the bottom line is
bottom-line-Y-offset: 0.8

# This decides how long will the chat bubble remain (in seconds)
stay-time: 8

# Plugin would send another line of bubble if the text's length exceeds a certain value
characters-per-line: 30

# Plugin would ignore player's chat message when its length is over a certain value
max-character-length: 100

# Cool down (seconds)
cool-down: 1