# namespace:font
minecraft:default:
  # default width
  default: 8
  # available font data template: unifont/ascii/nonlatin_european/accented/unicode(legacy)
  template-loading-sequence:
    - unifont
    - nonlatin_european
    - accented
    - ascii
  # The values here would override the same character in the template
  values:
    默: 8

minecraft:uniform:
  default: 8
  template-loading-sequence:
    - unifont

minecraft:alt:
  default: 8
  template-loading-sequence:
    - ascii_sga

minecraft:asciillager:
  default: 8
  template-loading-sequence:
    - asciillager

customcrops:default:
  default: 8
  template-loading-sequence: []
  values:
    뀁: -2
    뀂: 4
    뀃: 6
    뀄: 6
    뀅: 4

minecraft:customcrops:
  default: 8
  template-loading-sequence: []
  values:
    뀁: -2
    뀂: 4
    뀃: 6
    뀄: 6
    뀅: 4