# namespace:font
minecraft:default:
  # default width
  default: 8
  # Sets the loading sequence of the templates
  template-loading-sequence:
    - space
    - unifont
    - nonlatin_european
    - accented
    - ascii
  # The values here would override the same character in the template
  values:
    默: 8

minecraft:uniform:
  default: 8
  template-loading-sequence:
    - space
    - unifont

minecraft:alt:
  default: 8
  template-loading-sequence:
    - space
    - ascii_sga

minecraft:asciillager:
  default: 8
  template-loading-sequence:
    - space
    - asciillager

customcrops:default:
  default: 8
  template-loading-sequence: []
  values:
    뀁: -2
    뀂: 4
    뀃: 6
    뀄: 6
    뀅: 4

minecraft:customcrops:
  default: 8
  template-loading-sequence: []
  values:
    뀁: -2
    뀂: 4
    뀃: 6
    뀄: 6
    뀅: 4