# Team / Unlimited / Disable
mode: TEAM

# The duration (in seconds) that the nameplate preview will last for.
preview-duration: 5

# Default nameplate to display if player's nameplate is "none"
default-nameplate: 'none'

# This decides what %nameplates_prefix/suffix% would return
nameplate:
  refresh-frequency: 10
  prefix: ''
  player-name: '%player_name%'
  suffix: ''

# Settings for Team mode
team:
  # measured in ticks
  refresh-frequency: 10
  prefix: '%nameplates_prefix%'
  suffix: '%nameplates_suffix%'
  # Don't enable this if you are using a custom Tab plugin
  fix-Tab: false

# Settings for Unlimited mode
unlimited:
  tag_1:
    # The texts to display
    text: '%nameplates_nametag%'
    # Verticle offset of the fake entity
    vertical-offset: -1
    # Conditions (Owner side)
    owner-conditions:
      potion-effect: "INVISIBILITY<0"
      self-disguised: false  # Requires LibsDisguises
    # Conditions (Viewer side)
    viewer-conditions: { }
  tag_2:
    text: "IP: %player_ip%  My IP: %viewer_player_ip%"  # If a placeholder starts with "%viewer_", it would display the viewer's.
    vertical-offset: -0.7
    refresh-frequency: 10  # Decides the frequency of the text refreshing
    check-frequency: 20    # Decides the frequency of the condition check
    owner-conditions:
      potion-effect: "INVISIBILITY<0"
      self-disguised: false
    viewer-conditions:
      condition_1:
        type: permission
        value: 'nameplates.admin'