# Duration (in seconds) for which the nameplate preview will be displayed.
preview-duration: 5

# Default nameplate shown when a player's nameplate is set to "none."
default-nameplate: 'none'

# Configuration for nameplate behavior and appearance.
nameplate:
  # Frequency (in seconds) for refreshing the nameplate.
  refresh-frequency: 10
  # Prefix to be displayed before the player's name.
  # The prefix here will become part of the nameplate
  prefix: ''
  # Placeholder for the player's name
  player-name: '%player_name%'
  # Suffix to be displayed after the player's name.
  # The suffix here will become part of the nameplate
  suffix: ''

# Configuration for Unlimited tags.
unlimited:
  tag_1:
    # Text to be displayed for the tag.
    text: '%nameplates_nametag%'
    # Translation for the fake display entity.
    translation: 0,1,0
    # Conditions applicable on the owner side.
    owner-conditions:
      # Potion effect condition for invisibility.
      potion-effect: "INVISIBILITY<0"
      # Option to check if the owner is self-disguised.
      self-disguised: false
    # Conditions applicable for viewers (currently empty).
    viewer-conditions: { }
    # view-range: 1.0
    # shadow-radius: 0.0
    # shadow-strength: 1.0
    # scale: 1.0,1.0,1.0
    # line-width: 200
    # background-color: 64,0,0,0 # argb
    # alignment: CENTER
    # has-shadow: false
    # is-see-through: false
    # use-default-background-color: false
